### PR TITLE
update to asm 5.0.4

### PR DESCRIPTION
**Pull request by jtnord**
@reviewbybees 

[ASM 5.0.4 release notes](http://forge.ow2.org/forum/forum.php?forum_id=2467)
[ASM 5.0.3 release notes](http://forge.ow2.org/forum/forum.php?forum_id=2339)
[ASM 5.0.2 release notes](http://forge.ow2.org/forum/forum.php?forum_id=2320)

### CODE REVIEW

**Comment by stephenc** [comment]
:bee:

**Comment by jtnord** [comment]
@kohsuke asm 5.0.4 has been dropped from oss.sonatype.org staging without being promoted.  Can you republish it?

**Comment by jglick** [comment]
Yup was never actually released, sigh.

Anyway superseded by #9.

**Comment by oleg-nenashev** [comment]
asm6 has been integrated and release in #9

**Pull request closed without merging**
